stages:
  prepare_base_model:
    cmd: python src\pipelines\base_model_pipeline.py
    deps:
      - src\pipelines\base_model_pipeline.py
      - config\config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts\prepare_base_model
  training:
    cmd: python src/pipelines/training_pipeline.py
    deps:
      - src/pipelines/training_pipeline.py
      - config/config.yaml
      - artifacts/Chicken-fecal-images
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5
